spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/example?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "12345"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    deserialization:
      UNWRAP_ROOT_VALUE: true